# https://alacritty.org/config-alacritty.html

[general]
live_config_reload = true

[window]
option_as_alt = "Both"

[terminal.shell]
program = "/opt/homebrew/bin/fish"

[font]
normal = { family = "FiraCode Nerd Font Mono", style = "Regular" }
size = 16
offset = { x = 0, y = 2 }

[selection]
save_to_clipboard = true
