[[language]]
name = "rust"

[language.config]
cachePriming.enable = false
diagnostics.experimental.enable = true

[language-server.rust-analyzer.config.check]
command = "clippy"

[[language]]
name = "python"
auto-format = true

[[language]]
name = "go"
auto-format = true
