theme = "gruvbox_dark_hard"

[editor]
bufferline = "multiple"
line-number = "relative"
completion-trigger-len = 1
end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
cursor-line = "warning" # show warnings and errors on the cursorline inline

[editor.file-picker]
hidden = false
git-ignore = false

[editor.statusline]
left = [
  "mode",
  "spacer",
  "version-control",
  "spacer",
  "separator",
  "file-name",
  "file-modification-indicator"
]
right = [
  "spinner",
  "spacer",
  "workspace-diagnostics",
  "separator",
  "spacer",
  "diagnostics",
  "position",
  "file-encoding",
  "file-line-ending",
  "file-type"
]
separator = "╎"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
character = "╎"
render = true

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.whitespace]
render = "all"

[keys.normal]
C-a = "select_all"
K = "copy_selection_on_prev_line"
J = "copy_selection_on_next_line"
"$" = "goto_line_end"
"^" = "goto_first_nonwhitespace"
G = "goto_file_end"
"%" = "match_brackets"
y = "yank_to_clipboard"
Y = ":clipboard-yank-join"
p = "paste_clipboard_after"
P = "paste_clipboard_before"
R = "replace_selections_with_clipboard"
esc = ["collapse_selection", "keep_primary_selection"]
x = ["yank_to_clipboard", "delete_selection"]
s = "select_regex"
"?" = ["select_all", "search"]
i = ["insert_mode", "collapse_selection"]
a = ["append_mode", "collapse_selection"]

[keys.select]
"$" = "goto_line_end"
"^" = "goto_first_nonwhitespace"
G = "goto_file_end"
"%" = "match_brackets"
x = ["yank_to_clipboard", "delete_selection"]
y = "yank_to_clipboard"
Y = ":clipboard-yank-join"
p = "paste_clipboard_after"
P = "paste_clipboard_before"
R = "replace_selections_with_clipboard"
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
A-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
A-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
i = ["insert_mode", "collapse_selection"]
a = ["append_mode", "collapse_selection"]

[keys.normal.space]
"[" = "goto_previous_buffer"
"]" = "goto_next_buffer"
"=" = [":format", "select_all", ":pipe git stripspace"]
E = "workspace_diagnostics_picker"
P = "command_palette"
d = "hover"
e = "diagnostics_picker"
f = "file_picker_in_current_directory"
F = "file_picker"
space = "last_picker"
"B" = ":pipe-to ~/.config/helix/bin/git-blame.sh"
o = "jump_backward"
i = "jump_forward"
u = "switch_to_lowercase"
U = "switch_to_uppercase"
"+" = "increment"
"-" = "decrement"

# buffer
[keys.normal.space.b]
"q" = ":buffer-close"
"Q" = ":buffer-close!"
"p" = "buffer_picker"
"space" = "goto_previous_buffer"
"c" = ":buffer-close-all"
"C" = ":buffer-close-all!"
"k" = ":buffer-close-others"
"K" = ":buffer-close-others!"
"[" = ":buffer-previous"
"]" = ":buffer-next"
"r" = ":reload"
"R" = ":reload-all"
"n" = ":new"

[keys.normal.space.g]
r = ":reset-diff-change"
p = "changed_file_picker"

# toggle
[keys.normal.space.t]
"a" = ":toggle auto-completion"
"f" = ":toggle auto-format"
"h" = ":toggle lsp.display-inlay-hints"
"l" = ":toggle lsp.enabled"
"w" = ":toggle soft-wrap.enable"

# zen mode:
# ref: https://helix-editor-tutorials.com/tutorials/writing-documentation-and-prose-in-markdown-using-helix/
# > stty size
# 31 253
# (253 - 80) / 2 ~= 80 + 5 (where 5 being line numbers col width)
"z" = ":toggle gutters.line-numbers.min-width 80 5"

[keys.select.space]
u = "switch_to_lowercase"
U = "switch_to_uppercase"
"+" = "increment"
"-" = "decrement"
