theme = "gruvbox_dark_hard"

[editor]
true-color = true
auto-format = true
bufferline = "multiple"
line-number = "relative"
completion-trigger-len = 1

[editor.file-picker]
hidden = false
git-ignore = false

[editor.statusline]
left = [
  "mode",
  "spacer",
  "version-control",
  "spacer",
  "separator",
  "file-name",
  "file-modification-indicator"
]
right = [
  "spinner",
  "spacer",
  "workspace-diagnostics",
  "separator",
  "spacer",
  "diagnostics",
  "position",
  "file-encoding",
  "file-line-ending",
  "file-type"
]
separator = "╎"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
character = "╎"
render = true

[editor.lsp]
display-messages = true
display-inlay-hints = true

[keys.normal]
"/" = "toggle_comments"
C-j = "copy_selection_on_next_line"
C-k = "copy_selection_on_prev_line"
C-h = "jump_view_left"
C-l = "jump_view_right"
C-v = "vsplit"
J = "half_page_down"
K = "half_page_up"
"$" = "goto_line_end"
"^" = "goto_first_nonwhitespace"
G = "goto_file_end"
"%" = "match_brackets"
y = "yank_main_selection_to_clipboard"
p = "paste_clipboard_after"
P = "paste_clipboard_before"
esc = ["collapse_selection", "keep_primary_selection"]
x = "delete_selection"

[keys.select]
"$" = "goto_line_end"
"^" = "goto_first_nonwhitespace"
G = "goto_file_end"
"%" = "match_brackets"
y = "yank_main_selection_to_clipboard"
p = "paste_clipboard_after"
P = "paste_clipboard_before"
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]

[keys.normal.space]
"[" = "goto_previous_buffer" 
"]" = "goto_next_buffer"
E = "workspace_diagnostics_picker"
P = "command_palette"
d = "hover"
e = "diagnostics_picker"
p = "file_picker"
space = "goto_last_accessed_file"

[keys.select.space]
"/" = "toggle_comments"
