theme = "gruvbox_dark_hard"

[editor]
bufferline = "multiple"
line-number = "relative"
completion-trigger-len = 1
end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
cursor-line = "warning" # show warnings and errors on the cursorline inline

[editor.file-picker]
hidden = false
git-ignore = false

[editor.statusline]
left = [
  "mode",
  "spacer",
  "version-control",
  "spacer",
  "separator",
  "file-name",
  "file-modification-indicator"
]
right = [
  "spinner",
  "spacer",
  "workspace-diagnostics",
  "separator",
  "spacer",
  "diagnostics",
  "position",
  "file-encoding",
  "file-line-ending",
  "file-type"
]
separator = "╎"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
character = "╎"
render = true

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.whitespace]
render = "all"

[keys.normal]
C-a = "select_all"
K = "copy_selection_on_prev_line"
J = "copy_selection_on_next_line"
"$" = "goto_line_end"
"^" = "goto_first_nonwhitespace"
G = "goto_file_end"
w = ["move_next_word_start", "move_char_right", "collapse_selection"]
W = ["move_next_long_word_start", "move_char_right", "collapse_selection"]
e = ["move_next_word_end", "collapse_selection"]
E = ["move_next_long_word_end", "collapse_selection"]
b = ["move_prev_word_start", "collapse_selection"]
B = ["move_prev_long_word_start", "collapse_selection"]
"%" = "match_brackets"
y = "yank_to_clipboard"
Y = "yank_joined_to_clipboard"
p = "paste_clipboard_after"
P = "paste_clipboard_before"
R = "replace_selections_with_clipboard"
esc = ["collapse_selection", "keep_primary_selection"]
x = ["yank_to_clipboard", "delete_selection"]
s = "select_regex"
"?" = ["select_all", "search"]
A-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
A-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
i = ["insert_mode", "collapse_selection"]
a = ["append_mode", "collapse_selection"]
"+" = "increment"
"_" = "decrement"
j = "move_line_down"
k = "move_line_up"

[keys.normal.d]
d = ["extend_to_line_bounds", "yank_main_selection_to_clipboard", "delete_selection"]

[keys.select]
"{" = ["extend_to_line_bounds", "goto_prev_paragraph"]
"}" = ["extend_to_line_bounds", "goto_next_paragraph"]
0 = "goto_line_start"
"$" = "goto_line_end"
"^" = "goto_first_nonwhitespace"
G = "extend_to_file_end"
"%" = "match_brackets"
x = ["yank_to_clipboard", "delete_selection"]
y = "yank_to_clipboard"
Y = "yank_joined_to_clipboard"
p = "paste_clipboard_after"
P = "paste_clipboard_before"
R = "replace_selections_with_clipboard"
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
A-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
A-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
i = ["insert_mode", "collapse_selection"]
a = ["append_mode", "collapse_selection"]
"+" = "increment"
"_" = "decrement"
d = "delete_selection_noyank"

[keys.normal.space]
"[" = "goto_previous_buffer"
"]" = "goto_next_buffer"
"=" = [":format", "select_all", ":pipe git stripspace"]
d = "hover"
e = "diagnostics_picker"
E = "workspace_diagnostics_picker"
f = "file_picker_in_current_directory"
F = "file_picker"
i = "jump_forward"
o = "jump_backward"
P = "command_palette"
space = "last_picker"
u = "switch_to_lowercase"
U = "switch_to_uppercase"
x = "file_explorer_in_current_buffer_directory"
X = "file_explorer"

# buffer
[keys.normal.space.b]
"q" = ":buffer-close"
"Q" = ":buffer-close!"
"p" = "buffer_picker"
"space" = "goto_previous_buffer"
"c" = ":buffer-close-all"
"C" = ":buffer-close-all!"
"k" = ":buffer-close-others"
"K" = ":buffer-close-others!"
"[" = ":buffer-previous"
"]" = ":buffer-next"
"r" = ":reload"
"R" = ":reload-all"
"n" = ":new"

# git
[keys.normal.space.g]
_ = "@ git\n"
# show git log
l = ":sh git -C $(dirname $(realpath %{buffer_name})) log"
# show git line blame one-liner
b = ":sh git -C $(dirname $(realpath %{buffer_name})) blame -L %{cursor_line},%{cursor_line} $(realpath %{buffer_name})"
# show line blame commit
B = ":sh cd $(dirname $(realpath %{buffer_name})) && git show %sh{git blame -L %{cursor_line},+1 %{buffer_name} | awk '{ print $1 }' }"
r = ":reset-diff-change"
p = "changed_file_picker"

# toggle
[keys.normal.space.t]
"a" = ":toggle auto-completion"
"f" = ":toggle auto-format"
"h" = ":toggle lsp.display-inlay-hints"
"l" = ":toggle lsp.enabled"
"w" = ":toggle soft-wrap.enable"

[keys.select.space]
u = "switch_to_lowercase"
U = "switch_to_uppercase"
