# rust
[[language]]
name = "rust"

[language-server.rust-analyzer.config]
cargo.features = "all"
rust-analyzer.check.command = "clippy"
# rust-analyzer.inlayHints.typeHints.enable= false
# rust-analyzer.inlayHints.parameterHints.enable= false
# rust-analyzer.inlayHints.chainingHints.enable= false

# python
# pip3 install python-lsp-server[all] python-lsp-ruff black
[[language]]
name = "python"
auto-format = true

# go
# install lsp
# go get golang.org/x/tools/gopls@latest
# go get github.com/go-delve/delve/cmd/dlv@latest
[[language]]
name = "go"
auto-format = true
