# rust
[[language]]
name = "rust"

[language-server.rust-analyzer.config]
cargo.features = "all"
rust-analyzer.check.command = "clippy"

# python
# pip3 install python-lsp-server[all] python-lsp-ruff black
[[language]]
name = "python"
auto-format = true
formatter = { command = 'yapf', args = [] }

# go
# install lsp
# go get golang.org/x/tools/gopls@latest
# go get github.com/go-delve/delve/cmd/dlv@latest
[[language]]
name = "go"
auto-format = true

[[language]]
name = "html"
formatter = { command = 'prettier', args = ["--parser", "html"] }

[[language]]
name = "json"
formatter = { command = 'prettier', args = ["--parser", "json"] }

[[language]]
name = "css"
formatter = { command = 'prettier', args = ["--parser", "css"] }

[[language]]
name = "javascript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "typescript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

